name: tests

on:
  push:
    branches: [ main ]
    paths:
      - 'module_4/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'module_4/**'

permissions:
  contents: read

jobs:
  pytest:
    # If you want Windows too, change to a matrix (see note below)
    runs-on: ubuntu-latest

    # All `run:` commands below happen inside module_4
    defaults:
      run:
        working-directory: module_4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            module_4/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Make sure pytest & coverage are available even if not in requirements
          pip install pytest pytest-cov

      - name: Run tests (with coverage)
        run: |
          pytest -q --cov=src --cov-report=term-missing --cov-report=xml:coverage.xml
          coverage report > coverage_summary.txt || true

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: module_4/coverage_summary.txt
          retention-days: 14

      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: module_4/coverage.xml
          retention-days: 14
