import os
# psycopg literally just made this weird update (that is why it is not in the slides)
# it isn't even in replits documentation yet
import psycopg_pool
import psycopg


# Create a connection pool with a min_size of 0 and a max_size of 80. 
# Use the 'DATABASE_URL' environment variable to connect to the database.
# It is included in your Replit environment automatically (no need to set it up).
# This is also different than replits instructions (which literally worked until last week)
pool = psycopg_pool.ConnectionPool(os.environ['DATABASE_URL'])

#Get a connection from the pool.
conn = pool.getconn()

with conn.cursor() as cur:

  cur.execute("""
    DROP TABLE IF EXISTS courses;""")

  cur.execute("""
    DROP TABLE IF EXISTS students;""")

  cur.execute("""
    DROP TABLE IF EXISTS studentCourses;""")

  # Create our three tables
  cur.execute("""
    CREATE TABLE IF NOT EXISTS courses(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT,
      gpa REAL
      );""")

  cur.execute("""
      CREATE TABLE IF NOT EXISTS studentCourses(
      studentID int,
      courseID int
      );""")

  cur.execute("""
      CREATE TABLE IF NOT EXISTS students(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT
        );""")


  # Insert Data into our tables
  cur.execute("""
    INSERT INTO courses(id, name, gpa)
      VALUES (1, 'SQL Server', 3.2), (2, 'ASP.NET MVC', 3.5), (3,'MongoDB', 3.0), (4, 'Java', 2.5), (5, 'PHP', 3.3)
      ;""")

  cur.execute("""
    INSERT INTO students(id, name)
      VALUES (1, 'Sam'), (2, 'Mary'), (3, 'Tine')
    ;""")

  cur.execute("""
    INSERT INTO studentCourses(studentID, courseID)
      VALUES (1, 1), (1, 2), (1, 3), (2, 3), (2, 4), (3, 3), (3, 5)
  ;""")

  # Commit the changes to the database
  conn.commit()

# Close the connection
pool.putconn(conn)
conn.close()
