# .github/workflows/test.yml
name: module_4 tests

on:
  push:
    branches: [ main ]
    paths: [ 'module_4/**', '.github/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'module_4/**', '.github/workflows/**' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Start a DB the app can connect to at localhost:5432
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gradcafe
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gradcafe"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=24

    env:
      # If your app reads DATABASE_URL, set it explicitly (harmless if it also has a default).
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gradcafe

    defaults:
      run:
        working-directory: module_4

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-client

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage[toml]

      - name: Wait for Postgres to be ready
        env: { PGPASSWORD: postgres }
        run: |
          for i in {1..40}; do
            pg_isready -h localhost -p 5432 -U postgres -d gradcafe && break
            sleep 1
          done
          psql -h localhost -U postgres -d gradcafe -c 'select 1;'

      - name: Run tests with covera
