name: module_4 tests

on:
  push:
    branches: [ main ]
    paths:
      - 'module_4/**'             # only run when module_4 changes
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'module_4/**'
      - '.github/workflows/**'
  workflow_dispatch:              # allow manual run from Actions tab

jobs:
  test:
    runs-on: ubuntu-latest        # or add a matrix for Windows too
    defaults:
      run:
        working-directory: module_4   # all commands run inside module_4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional: extra tools used below
          pip install pytest pytest-cov coverage[toml]

      - name: Run tests with coverage
        run: |
          pytest -q --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=1
          coverage xml -o coverage.xml
          coverage report > coverage_summary.txt

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: module_4/coverage_summary.txt
